### ISSUE TITLE
error: failed to parse BibLaTeX file (../zotero-autoexport.bib:28: unknown editor type)

### ISSUE THREAD

**Issue by pbsds** [typst/biblatex#52]
Error:

```
error: failed to parse BibLaTeX file (../zotero-autoexport.bib:28: unknown editor type)
```

Offending biblatex entry, as generated by `zotero-better-bibtex`

```bib
@video{acerolaThisDifferenceGaussians2022,
  entrysubtype = {video},
  title = {This Is the {{Difference}} of {{Gaussians}}},
  editor = {{Acerola}},
  editortype = {director},
  date = {2022-12-24},
  url = {https://www.youtube.com/watch?v=5EuYKEvugLU},
  urldate = {2023-09-16},
  abstract = {In the realm of image based edge detection, aesthetically pleasing edges are hard to come by. But, what if we could get stylized edge lines by just blurring our image twice? Download my GShade shader pack! https://github.com/GarrettGunnell/Ace... Patreon: https://www.patreon.com/acerola\_t Twitter: https://twitter.com/Acerola\_t Twitch: https://www.twitch.tv/acerola\_t Code: https://github.com/GarrettGunnell/Pos... Join My Discord Server! https://discord.gg/FxGQvbfm6Y References: https://users.cs.northwestern.edu/\textasciitilde sc... Music: Sandgem Town (Day) - Pokemon Diamond OST Joy - Persona 3 During The Test - Persona 3 Afternoon Break - Persona 3 This Mysterious Feeling - Persona 3 Muscle Blues - Persona 4 Like A Dream Come True - Persona 4 Soft Oversight - Sonny Boy OST Summer Storm - Sonny Boy OST ソウとセイジ - Sonny Boy OST arrow in thumbnail drawn by thlurp Thanks for watching! This video is dedicated to my friend, Alotryx. \#acerola \#graphics \#gamedev \#unity3d \#graphics \#shaders}
}
```

Removing the  `editor = ...` line fixes the issue.

## Desired solution

1. ignore or dump all unrecognized entries into a hashmap and raise a warning,

and optionally

2. handle the `editor` tag for `@video`

**Comment by quachpas** [comment]
Hello @pbsds, the library follows strictly the implementation of biblatex. The listed editor types are "editor, compiler, founder, continuator, redactor, reviser, collaborator, organizer." Unfortunately, biblatex errors on unknown editortypes atm.

@reknih, do you have an opinion on how to proceed? Should we add support arbitrary editortypes? Or raise a warning instead of an error?

e.g., [Chicago 17th](https://texlive.mycozy.space/macros/latex/contrib/biblatex-contrib/biblatex-chicago/doc/biblatex-chicago.pdf) has "conductor, director, producer, and, oddly, none"

Looking at biblatex-chicago, seems like it accepts arbitrary editortypes 
> The 17th edition (14.263) also seems to favor, in some circumstances, using strings to identify individual performers, e.g., “vocalist” or “pianist,” so even though there’s no \bibstring associated with these types you can now provide them, or anything else you need, in whatever form (“vocalist” or “sung by”) suits your citation.

Some examples bib from biblatex-chicago: [2] [3]

[1] https://github.com/retorquere/zotero-better-bibtex/issues/365#issuecomment-1904427123
[2] https://mirrors.ircam.fr/pub/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-chicago/doc/notes-test.bib
[3] https://mirrors.ircam.fr/pub/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-chicago/doc/dates-test.bib

**Comment by elipousson** [comment]
I just ran into this same issue and would note that I believe the Zotero citation management tool is set up to use director by default for video references. I can use contributor but this may be a limitations that other Zotero users will keep running into.

**Comment by Ardhanaariishvara** [comment]
Hello, I also ran into the issue, I had to omit the field at export through the Better BibTex plugin.
